//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taro.Resources
{
    using System;
    using System.Collections.Generic;
    
    public partial class Glossaries
    {
        public int id { get; set; }
        public string Definition { get; set; }
        public string Description { get; set; }
    }
}
