//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taro.Resources
{
    using System;
    using System.Collections.Generic;
    
    public partial class LessonDB
    {
        public int id { get; set; }
        public string Lesson { get; set; }
        public Nullable<int> NumberPage { get; set; }
        public byte[] Image { get; set; }
    }
}
